import { useQuery } from '@tanstack/react-query';
import type { Opportunity } from '@/components/OpportunityTable';

interface OpportunitiesParams {
  buyRegion: number;
  sellRegion: number;
}

interface OpportunitiesResponse {
  opportunities: Opportunity[];
  meta: {
    lastUpdated: string;
    buyRegion: number;
    sellRegion: number;
    buyRegionName: string;
    sellRegionName: string;
  };
}

/**
 * Fetch opportunities from static JSON files (static-cache architecture)
 * Files are pre-generated by GitHub Actions and served from Vercel Edge CDN
 */
async function fetchOpportunities(
  params: OpportunitiesParams
): Promise<OpportunitiesResponse> {
  // Fetch from static JSON file: /data/{buyRegion}-{sellRegion}.json
  const response = await fetch(`/data/${params.buyRegion}-${params.sellRegion}.json`);

  if (!response.ok) {
    if (response.status === 404) {
      throw new Error(`No data available for this region pair. Try a different combination.`);
    }
    throw new Error('Failed to fetch opportunities');
  }

  const json = await response.json();

  return {
    opportunities: json.opportunities || [],
    meta: {
      lastUpdated: json.lastUpdated,
      buyRegion: json.buyRegion,
      sellRegion: json.sellRegion,
      buyRegionName: json.buyRegionName,
      sellRegionName: json.sellRegionName,
    },
  };
}

export function useOpportunities(params: OpportunitiesParams | null) {
  return useQuery({
    queryKey: ['opportunities', params?.buyRegion, params?.sellRegion],
    queryFn: () => fetchOpportunities(params!),
    enabled: params !== null && params.buyRegion !== params.sellRegion,
    staleTime: 5 * 60 * 1000, // 5 minutes
  });
}
